# Generated by Django 2.1.1 on 2019-07-22 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.PositiveIntegerField()),
                ('income_growth', models.FloatField()),
                ('spending', models.PositiveIntegerField()),
                ('inflation', models.FloatField()),
                ('savings', models.PositiveIntegerField()),
                ('current_age', models.PositiveIntegerField()),
                ('death_age', models.PositiveIntegerField()),
                ('retirement_age', models.PositiveIntegerField()),
                ('investment_risk', models.PositiveIntegerField(choices=[(1, 'Extremely Safe'), (3, 'Low Risk'), (5, 'Moderate Risk'), (7, 'Risky'), (9, 'Very Risky')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
