# Generated by Django 2.1.1 on 2019-07-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinfo',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='default_slug', unique=True),
        ),
    ]
