# Generated by Django 2.1.1 on 2019-07-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190722_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinfo',
            name='FWB1_3',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Very little', 'Very little'), ('Somewhat', 'Somewhat'), ('Very well', 'Very well'), ('Completely', 'Completely'), ('Refused', 'Refused')], default='Refused', max_length=300),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='FWB1_5',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Very little', 'Very little'), ('Somewhat', 'Somewhat'), ('Very well', 'Very well'), ('Completely', 'Completely'), ('Refused', 'Refused')], default='Refused', max_length=300),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='FWB1_6',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Very little', 'Very little'), ('Somewhat', 'Somewhat'), ('Very well', 'Very well'), ('Completely', 'Completely'), ('Refused', 'Refused')], default='Refused', max_length=300),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='FWB2_1',
            field=models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often'), ('Always', 'Always'), ('Refused', 'Refused')], default='Refused', max_length=300),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='FWB2_3',
            field=models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often'), ('Always', 'Always'), ('Refused', 'Refused')], default='Refused', max_length=300),
        ),
    ]
